public class AdditionOfNumbers {
    
    public static void Addition(){
        Integer var1 = 5 , var2 = 6, sum;
        sum= var1 + var2;
        System.debug(' Result or Addition =  ' + sum); 
    }
    public static void Subtraction(){
        Integer var1 = 18 , var2 = 5, sub;
        sub =var1 - var2;
        System.debug(' Result or Addition =  ' + sub); 
    }
    public static void Multiplication(Integer var1,Integer var2){
        Integer mul;
        mul =var1*var2;
        System.debug(' multiplication  =  ' + mul); 
    }
    public static void Division(Integer var1,Integer var2){
        Integer div;
        div =var1/var2;
        System.debug(' multiplication  =  ' + div); 
    }
}