public class ArithematicOperation {
    public integer sum(integer number1,integer number2){
        integer sum = number1+number2;
        System.debug('The Sum of 2 numbers is '+sum);
        return sum;
        
    }
    public void sum1(Integer number1, Integer number2 ,Integer number3){ // parameters
Integer sum = number1 + number2 + number3;
System.debug('The Sum of 3 numbers is '+sum);
}
}